
field_separator: "	"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
LABEL_FIELD: label
TIME_FIELD: timestamp

load_col:
    inter: [user_id, item_id, label, timestamp]
    user: [user_id]
    item: [item_id, year, writer, title, genre, director]

eval_args:
    split: {'RS': [8, 1, 1]}
    group_by: user
    order: RO
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision', 'MAP']
topk: 10
valid_metric: Recall@10
